version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo_container
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: husnain117/scdfp-backend:latest
    container_name: backend_container
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/tododb
      - PORT=5000
    depends_on:
      - mongo

  frontend:
    image: husnain117/scdfp-frontend:latest
    container_name: frontend_container
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:

