# Backend deployment configuration for SCD FP application
# This is a test change to trigger the GitHub Actions workflow
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: scd-fp
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: husnain117/scdfp-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: mongodb://mongodb-service:27017/tododb
        - name: PORT
          value: "5000"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: backend
  type: ClusterIP
