name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        eval $(minikube docker-env)

    - name: Build Backend Docker image
      run: |
        docker build -t husnain117/scdfp-backend:latest -f backend/Dockerfile .

    - name: Build Frontend Docker image
      run: |
        docker build -t husnain117/scdfp-frontend:latest -f frontend/Dockerfile .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Backend image to Docker Hub
      run: docker push husnain117/scdfp-backend:latest

    - name: Push Frontend image to Docker Hub
      run: docker push husnain117/scdfp-frontend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/backend-config.yaml
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/frontend-configmap.yaml
        kubectl apply -f k8s/mongodb-deployment.yaml
        kubectl apply -f k8s/mongodb-pvc.yaml
        kubectl apply -f k8s/mongodb-secrets.yaml
        kubectl apply -f k8s/mongodb-service.yaml

    - name: Verify Deployment
      run: |
        echo "Checking pods..."
        kubectl get pods -n scd-fp
        echo "Checking services..."
        kubectl get services -n scd-fp
        echo "Checking deployments..."
        kubectl get deployments -n scd-fp
